<?php

function apip_debug_imdb_content() {
    $content = array(
        "Title"=>"Guardians of the Galaxy Vol. 2",
        "Year"=>"2017",
        "Rated"=>"PG-13",
        "Released"=>"05 May 2017",
        "Runtime"=>"136 min",
        "Genre"=>"Action, Adventure, Sci-Fi",
        "Director"=>"James Gunn",
        "Writer"=>"James Gunn, Dan Abnett (based on the Marvel comics by), Andy Lanning (based on the Marvel comics by), Steve Englehart (Star-lord created by), Steve Gan (Star-lord created by), Jim Starlin (Gamora and Drax created by), Stan Lee (Groot created by), Larry Lieber (Groot created by), Jack Kirby (Groot created by), Bill Mantlo (Rocket Raccoon created by), Keith Giffen (Rocket Raccoon created by), Steve Gerber (Howard the Duck created by), Val Mayerik (Howard the Duck created by)",
        "Actors"=>"Chris Pratt, Zoe Saldana, Dave Bautista, Vin Diesel",
        "Plot"=>"The Guardians must fight to keep their newfound family together as they unravel the mystery of Peter Quill's true parentage.",
        "Language"=>"English",
        "Country"=>"USA, New Zealand, Canada",
        "Awards"=>"6 wins & 13 nominations.",
        "Poster"=>"https://images-na.ssl-images-amazon.com/images/M/MV5BMTg2MzI1MTg3OF5BMl5BanBnXkFtZTgwNTU3NDA2MTI@._V1_SX300.jpg",
        "Metascore"=>"67",
        "imdbRating"=>"7.8",
        "imdbVotes"=>"301,863",
        "imdbID"=>"tt3896198",
        "Type"=>"movie",
        "DVD"=>"22 Aug 2017",
        "BoxOffice"=>"$389,804,217",
        "Production"=>"Walt Disney Pictures",
        "Website"=>"https://marvel.com/guardians",
        "Response"=>"True"
    );
    return $content;
}

function apip_debug_book_content() {
    $books =array(
        "rating"=>array(
                "max"=>10,
                "numRaters"=>43,
                "average"=>"8.0",
                "min"=>0),
        "subtitle"=>"",
        "author"=>array("array(法)爱德华·路易斯（Édouard Louis）",),
        "pubdate"=>"2019-9-1",
        "tags"=>array(array("count"=>32,"name"=>"LGBT","title"=>"LGBT"),
                array("count"=>27,"name"=>"法国","title"=>"法国"),
                array("count"=>24,"name"=>"外国文学","title"=>"外国文学"),
                array("count"=>23,"name"=>"同性","title"=>"同性"),
                array("count"=>21,"name"=>"跨性别者成长纪实","title"=>"跨性别者成长纪实"),
                array("count"=>15,"name"=>"偏见","title"=>"偏见"),
                array("count"=>13,"name"=>"2019","title"=>"2019"),
                array("count"=>11,"name"=>"自传","title"=>"自传")),
        "origin_title"=>"En finir avec Eddy Bellegueule",
        "image"=>"https://img9.doubanio.com\/view\/subject\/m\/public\/s33461756.jpg",
        "binding"=>"平装",
        "translator"=>array("赵玥",),
        "catalog"=>"庇卡底\n相逢\n父亲\n举止\n在学校\n痛苦\n男人的角色\n我母亲早晨的画像\n母亲的生活掠影\n父母的卧室\n女孩、母亲和祖母们的生活\n村里的故事\n良好的教育\n父亲的另一面\n男人们对医疗的抗拒\n希尔万（见证）\n失败与逃避\n棚子事件\n棚子事件之后\n变化\n劳拉\n身体的反抗\n恋爱的终极尝试：萨布丽娜\n恶心\ndi一次尝试逃走\n窄门\n尾声",
        "pages"=>"200",
        "images"=>array("small"=>"https://img9.doubanio.com\/view\/subject\/s\/public\/s33461756.jpg","large"=>"https://img9.doubanio.com\/view\/subject\/l\/public\/s33461756.jpg","medium"=>"https://img9.doubanio.com\/view\/subject\/m\/public\/s33461756.jpg"),
        "alt"=>"https://book.douban.com\/subject\/34782539\/",
        "id"=>"34782539",
        "publisher"=>"四川文艺出版社",
        "isbn10"=>"7541154814",
        "isbn13"=>"9787541154812",
        "title"=>"艾迪的告别",
        "url"=>"https://api.douban.com\/v2\/book\/34782539",
        "alt_title"=>"En finir avec Eddy Bellegueule",
        "author_intro"=>"【作者】\n爱德华•路易斯（Édouard Louis），原名艾迪•贝勒格勒，小说家、编辑，1992年出生在法国，《艾迪的告别》是他首部自传体小说。已出版作品还有《暴力史》《谁杀了我父亲》。\n【译者】\n赵玥，巴黎索邦大学法国文学博士，目前在四川大学外国语学院法语专业任教。翻译的作品有《世界上可爱的东西太多，我不能什么都想要》《局外人》《鼠疫》等。",
        "summary"=>"开始不会想到逃，因为还不知道存在着别处。\n这是当代法国一个封闭落后的小镇，这里住着一群终日醉醺醺的“硬汉”和疲惫不堪的“悍妇”。这里的孩子全都野蛮生长，男孩以打架、逃学，早早当上硬汉，去工厂做工为荣。女孩则以早早结婚生子为己任。但艾迪却是个天生敏感脆弱的异类，一个“一点不像男孩”的男孩。他的存在，仿佛挑畔了整个家族和小镇的价值观，成了众矢之的。\n日复一日，艾迪默默忍受着同学的霸凌，邻里的讥讽，甚至亲人的嫌弃。所有渴求都得不到回应，每个早晨都在巨大的焦虑中开始胆战心惊的一天……为了摆脱孤立，得到认同，他竭尽全力回归“正轨”，模仿“硬汉”，骂脏话、踢足球、交女友。然而，改变天性就意味着必须泯灭本性，放逐自我，活成另一个人，这甚至比遭受唾弃更令他绝望。最后，似乎只剩下一条几乎行不通的路可走，那就是逃离……",
        "price"=>"39.80元"
    );
    return $books;
}

function apip_debug_movie_content() {
    $movie = array(
        "rating"=>array(
          "max"=>10,
          "average"=>8.3,
          "stars"=>"45",
          "min"=>0
        ),
        "reviews_count"=>5736,
        "wish_count"=>59987,
        "douban_site"=>"",
        "year"=>"2018",
        "images"=>array(
          "small"=>"http://img3.doubanio.com/view/photo/s_ratio_poster/public/p2514119443.jpg",
          "large"=>"http://img3.doubanio.com/view/photo/s_ratio_poster/public/p2514119443.jpg",
          "medium"=>"http://img3.doubanio.com/view/photo/s_ratio_poster/public/p2514119443.jpg"
        ),
        "alt"=>"https://movie.douban.com/subject/26861685/",
        "id"=>"26861685",
        "mobile_url"=>"https://movie.douban.com/subject/26861685/mobile",
        "title"=>"红海行动",
        "do_count"=>null,
        "share_url"=>"http://m.douban.com/movie/subject/26861685",
        "seasons_count"=>null,
        "schedule_url"=>"",
        "episodes_count"=>null,
        "countries"=>array(
          "中国大陆",
          "香港"
        ),
        "genres"=>array(
          "动作",
          "战争"
        ),
        "collect_count"=>810900,
        "casts"=>array(
          array(
            "alt"=>"https://movie.douban.com/celebrity/1274761/",
            "avatars"=>array(
              "small"=>"http://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1489386626.47.jpg",
              "large"=>"http://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1489386626.47.jpg",
              "medium"=>"http://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1489386626.47.jpg"
            ),
            "name"=>"张译",
            "id"=>"1274761"
          ),
          array(
            "alt"=>"https://movie.douban.com/celebrity/1354442/",
            "avatars"=>array(
              "small"=>"http://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1515637640.69.jpg",
              "large"=>"http://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1515637640.69.jpg",
              "medium"=>"http://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1515637640.69.jpg"
            ),
            "name"=>"黄景瑜",
            "id"=>"1354442"
          ),
          array(
            "alt"=>"https://movie.douban.com/celebrity/1272245/",
            "avatars"=>array(
              "small"=>"http://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p49399.jpg",
              "large"=>"http://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p49399.jpg",
              "medium"=>"http://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p49399.jpg"
            ),
            "name"=>"海清",
            "id"=>"1272245"
          ),
          array(
            "alt"=>"https://movie.douban.com/celebrity/1322949/",
            "avatars"=>array(
              "small"=>"http://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1502100680.45.jpg",
              "large"=>"http://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1502100680.45.jpg",
              "medium"=>"http://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1502100680.45.jpg"
            ),
            "name"=>"杜江",
            "id"=>"1322949"
          )
        ),
        "current_season"=>null,
        "original_title"=>"红海行动",
        "summary"=>"中东国家伊维亚共和国发生政变，武装冲突不断升级。刚刚在索马里执行完解救人质任务的海军护卫舰临沂号，受命前往伊维亚执行撤侨任务。舰长高云（张涵予 饰）派出杨锐（张译 饰）率领的蛟龙突击队登陆战区，护送华侨安全撤离。谁知恐怖组织扎卡却将撤侨部队逼入交火区，一场激烈的战斗在所难免。与此同时，法籍华人记者夏楠（海清 饰）正在伊维亚追查威廉·柏森博士贩卖核原料的事实，而扎卡则突袭柏森博士所在的公司，意图抢走核原料。混战中，一名隶属柏森博士公司的中国员工成为人质。为了解救该人质，八名蛟龙队员必须潜入有150名恐怖分子的聚集点，他们用自己的信念和鲜血铸成中国军人顽强不屈的丰碑！\n本片根据也门撤侨事件改编。©豆瓣",
        "subtype"=>"movie",
        "directors"=>array(
          array(
            "alt"=>"https://movie.douban.com/celebrity/1275075/",
            "avatars"=>array(
              "small"=>"http://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1372934445.18.jpg",
              "large"=>"http://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1372934445.18.jpg",
              "medium"=>"http://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1372934445.18.jpg"
            ),
            "name"=>"林超贤",
            "id"=>"1275075"
          )
        ),
        "comments_count"=>190376,
        "ratings_count"=>583555,
        "aka"=>array(
          "刀锋·红海行动",
          "Operation Red Sea"
        )
      );
      return $movie;
}

function apip_debug_book_series_content(){
  $books = array(
    "count"=>20,
    "start"=>0,
    "total"=>21,
    "books"=>array(
      array(
        "rating"=>array(
          "max"=>10,
          "numRaters"=>1126,
          "average"=>"8.4",
          "min"=>0
        ),
        "subtitle"=>"",
        "author"=>array(
          "松井優征"
        ),
        "pubdate"=>"2012-11-2",
        "tags"=>array(
          array(
            "count"=>363,
            "name"=>"漫画",
            "title"=>"漫画"
          ),
          array(
            "count"=>161,
            "name"=>"日本",
            "title"=>"日本"
          ),
          array(
            "count"=>147,
            "name"=>"松井優征",
            "title"=>"松井優征"
          ),
          array(
            "count"=>92,
            "name"=>"日本漫画",
            "title"=>"日本漫画"
          ),
          array(
            "count"=>77,
            "name"=>"暗殺教室",
            "title"=>"暗殺教室"
          ),
          array(
            "count"=>74,
            "name"=>"松井优征",
            "title"=>"松井优征"
          ),
          array(
            "count"=>67,
            "name"=>"搞笑",
            "title"=>"搞笑"
          ),
          array(
            "count"=>59,
            "name"=>"JUMP",
            "title"=>"JUMP"
          )
        ),
        "origin_title"=>"",
        "image"=>"https://img3.doubanio.com/view/subject/m/public/s23126384.jpg",
        "binding"=>"新書判",
        "translator"=>array(),
        "catalog"=>"第01话 暗杀の时间\n第02话 野球の时间\n第03话 杀必死的时间\n第04话 基础课时间\n第05话 业的时间\n第06话 二选一的时间array(2)\n番外篇 休息时间 杀老师的绘画歌\n第07话 毒理课的时间array(2)\n第08话 胸部的时间\n第09话 大人的时间",
        "pages"=>"184",
        "images"=>array(
          "small"=>"https://img3.doubanio.com/view/subject/s/public/s23126384.jpg",
          "large"=>"https://img3.doubanio.com/view/subject/l/public/s23126384.jpg",
          "medium"=>"https://img3.doubanio.com/view/subject/m/public/s23126384.jpg"
        ),
        "alt"=>"https://book.douban.com/subject/19949958/",
        "id"=>"19949958",
        "publisher"=>"集英社",
        "isbn10"=>"4088705963",
        "isbn13"=>"9784088705965",
        "title"=>"暗殺教室 1",
        "url"=>"https://api.douban.com/v2/book/19949958",
        "alt_title"=>"",
        "author_intro"=>"松井优征（まつい ゆうせい）\n诞生日：1981年1月31日\n出身地：埼玉县 sK^ YJf?8~\n特技/兴趣：模仿フカキョン的样子\n睫毛长，是左撇子\n喜欢的颜色是肤色\n是巨人队的球迷\n父亲是武藏野音乐大学副教授&合唱指挥的松井彻\n在周刊少年JUMP连载的卷末说过，每个礼拜老是一直在吃豆芽锅\n主食是崇慕者来信的火锅（加点插图更美味）\n『JOJO奇妙冒险』（荒木飞吕彦）的Fans\n以前曾担任泽井启夫（鼻毛真拳）的助手，在其单行本有插画\n从小学1~2年级开始画漫画\n涅罗初次亮相的时候，审查员是草莓100%的河下水希\n松井曰：「人间は牛乳とホウレン草だけで生きられる」\n（人类只能靠牛奶跟菠菜活下去）\n经历\n2000年『ラビングデッド』在第五十一回天下一漫画赏－铃木赏（铃木央）\n2004年『魔人侦探脑噛涅罗』在十二杰漫画赏准入选\n2005年『周刊少年JUMP』杂志上『魔人侦探脑噛涅罗』连载开始\n2012年『周刊少年JUMP』杂志上『暗杀教室』连载开始\n作品\n『魔人侦探脑噛涅罗』单行本目前日本出版至第二十三集（已完结），台湾目前出版至第十八集\n『离婚调停』 SQ短篇发表\n『东京百货战争体验记』短篇2011年发表\n评价\n*独特的世界设定、有冲击力的画风、\n有个性的人物角色、以及毒舌的讽刺等等，\n在独创性的领域之内获得相当高的评价的新人作者。\n特别是在被说有循守旧化的『少年JUMP』中，被说是担任相当重要的位置。\n*以插画画家石原豪人当作范本，有些使人毛骨悚然的图也是受他影响。\n作画特征：配合作品的场面，意图的无视远近法大胆的变形作画等等，\n多次使用让人想到表现主义的绘图。\n『魔人侦探脑啮涅罗』中第4话，被那出奇的绘画在网路上引起广大的回响，\n之後也受到网友的热烈支持。\n*基本上在绘画功力上尚未纯熟，门开启的方向相反等等、有六只手指等等，\n拿东西的手变成另一只等等．非常随性的作画（典型的错误）。\n随著连载的持续，在建筑物或是背景等等，质感表现也逐渐进步。\n顺便一提，对於左右的区分相当苦手（拿东西的手会不经意的画反…等习惯，编辑部似乎放宽了标准。）\n（出道时的评价）\n*入围12月期十二节赏的『魔人侦探脑啮涅罗』，那游刃有馀的独创性，高度的演出力◎这两点．\n（角色人物、独特性）○两点（故事、演出）获得高度的评价。\n在绘画方面获得「今後会越来越期待」评价。",
        "summary"=>"号令と共に教室を満たす銃声! 椚ヶ丘中学校3年E組は生徒全員が先生の命を狙う暗殺教室。教師と生徒、標的と暗殺者の異常な日常が始まる――!!",
        "series"=>array(
          "id"=>"15153",
          "title"=>"暗殺教室"
        ),
        "price"=>"JPY 420"
      ),
      array(
        "rating"=>array(
          "max"=>10,
          "numRaters"=>447,
          "average"=>"9.0",
          "min"=>0
        ),
        "subtitle"=>"",
        "author"=>array(
          "松井 優征"
        ),
        "pubdate"=>"2012-12-28",
        "tags"=>array(
          array(
            "count"=>130,
            "name"=>"漫画",
            "title"=>"漫画"
          ),
          array(
            "count"=>82,
            "name"=>"松井優征",
            "title"=>"松井優征"
          ),
          array(
            "count"=>58,
            "name"=>"日本",
            "title"=>"日本"
          ),
          array(
            "count"=>37,
            "name"=>"暗殺教室",
            "title"=>"暗殺教室"
          ),
          array(
            "count"=>31,
            "name"=>"日本漫画",
            "title"=>"日本漫画"
          ),
          array(
            "count"=>21,
            "name"=>"松井优征",
            "title"=>"松井优征"
          ),
          array(
            "count"=>17,
            "name"=>"少年漫画",
            "title"=>"少年漫画"
          ),
          array(
            "count"=>14,
            "name"=>"搞笑",
            "title"=>"搞笑"
          )
        ),
        "origin_title"=>"",
        "image"=>"https://img3.doubanio.com/view/subject/m/public/s24517454.jpg",
        "binding"=>"新書判",
        "translator"=>array(),
        "catalog"=>"",
        "pages"=>"200",
        "images"=>array(
          "small"=>"https://img3.doubanio.com/view/subject/s/public/s24517454.jpg",
          "large"=>"https://img3.doubanio.com/view/subject/l/public/s24517454.jpg",
          "medium"=>"https://img3.doubanio.com/view/subject/m/public/s24517454.jpg"
        ),
        "alt"=>"https://book.douban.com/subject/20398568/",
        "id"=>"20398568",
        "publisher"=>"集英社",
        "isbn10"=>"4088706048",
        "isbn13"=>"9784088706047",
        "title"=>"暗殺教室 2",
        "url"=>"https://api.douban.com/v2/book/20398568",
        "alt_title"=>"",
        "author_intro"=>"",
        "summary"=>"E組に新たに配属された美人外国語教師。彼女の正体は美貌と巧みな話術で対象に近付く凄腕の殺し屋だった!! 殺せんせー暗殺の準備が着々と進み…!?",
        "series"=>array(
          "id"=>"15153",
          "title"=>"暗殺教室"
        ),
        "price"=>"JPY 420"
      ),
      array(
        "rating"=>array(
          "max"=>10,
          "numRaters"=>362,
          "average"=>"9.0",
          "min"=>0
        ),
        "subtitle"=>"",
        "author"=>array(
          "松井 優征"
        ),
        "pubdate"=>"2013-3-4",
        "tags"=>array(
          array(
            "count"=>106,
            "name"=>"漫画",
            "title"=>"漫画"
          ),
          array(
            "count"=>65,
            "name"=>"松井優征",
            "title"=>"松井優征"
          ),
          array(
            "count"=>48,
            "name"=>"日本",
            "title"=>"日本"
          ),
          array(
            "count"=>31,
            "name"=>"日本漫画",
            "title"=>"日本漫画"
          ),
          array(
            "count"=>27,
            "name"=>"暗殺教室",
            "title"=>"暗殺教室"
          ),
          array(
            "count"=>19,
            "name"=>"松井优征",
            "title"=>"松井优征"
          ),
          array(
            "count"=>14,
            "name"=>"搞笑",
            "title"=>"搞笑"
          ),
          array(
            "count"=>11,
            "name"=>"日漫",
            "title"=>"日漫"
          )
        ),
        "origin_title"=>"",
        "image"=>"https://img3.doubanio.com/view/subject/m/public/s25505516.jpg",
        "binding"=>"新書判",
        "translator"=>array(),
        "catalog"=>"",
        "pages"=>"192",
        "images"=>array(
          "small"=>"https://img3.doubanio.com/view/subject/s/public/s25505516.jpg",
          "large"=>"https://img3.doubanio.com/view/subject/l/public/s25505516.jpg",
          "medium"=>"https://img3.doubanio.com/view/subject/m/public/s25505516.jpg"
        ),
        "alt"=>"https://book.douban.com/subject/21319184/",
        "id"=>"21319184",
        "publisher"=>"集英社",
        "isbn10"=>"4088706331",
        "isbn13"=>"9784088706337",
        "title"=>"暗殺教室 3",
        "url"=>"https://api.douban.com/v2/book/21319184",
        "alt_title"=>"",
        "author_intro"=>"",
        "summary"=>"修学旅行中に拉致された茅野と神崎!! 渚達は殺せんせーが用意したしおりで2人の行方を探る。そして京都で繰り広げられる殺せんせー暗殺の行方は!?",
        "series"=>array(
          "id"=>"15153",
          "title"=>"暗殺教室"
        ),
        "price"=>"JPY 420"
      ),
      array(
        "rating"=>array(
          "max"=>10,
          "numRaters"=>304,
          "average"=>"9.1",
          "min"=>0
        ),
        "subtitle"=>"",
        "author"=>array(
          "松井 優征"
        ),
        "pubdate"=>"2013-5-2",
        "tags"=>array(
          array(
            "count"=>80,
            "name"=>"漫画",
            "title"=>"漫画"
          ),
          array(
            "count"=>58,
            "name"=>"松井優征",
            "title"=>"松井優征"
          ),
          array(
            "count"=>37,
            "name"=>"日本",
            "title"=>"日本"
          ),
          array(
            "count"=>23,
            "name"=>"暗殺教室",
            "title"=>"暗殺教室"
          ),
          array(
            "count"=>19,
            "name"=>"日本漫画",
            "title"=>"日本漫画"
          ),
          array(
            "count"=>14,
            "name"=>"松井优征",
            "title"=>"松井优征"
          ),
          array(
            "count"=>9,
            "name"=>"搞笑",
            "title"=>"搞笑"
          ),
          array(
            "count"=>7,
            "name"=>"少年漫画",
            "title"=>"少年漫画"
          )
        ),
        "origin_title"=>"",
        "image"=>"https://img3.doubanio.com/view/subject/m/public/s26378859.jpg",
        "binding"=>"コミック",
        "translator"=>array(),
        "catalog"=>"",
        "pages"=>"192",
        "images"=>array(
          "small"=>"https://img3.doubanio.com/view/subject/s/public/s26378859.jpg",
          "large"=>"https://img3.doubanio.com/view/subject/l/public/s26378859.jpg",
          "medium"=>"https://img3.doubanio.com/view/subject/m/public/s26378859.jpg"
        ),
        "alt"=>"https://book.douban.com/subject/22488285/",
        "id"=>"22488285",
        "publisher"=>"集英社",
        "isbn10"=>"4088706676",
        "isbn13"=>"9784088706672",
        "title"=>"暗殺教室 4",
        "url"=>"https://api.douban.com/v2/book/22488285",
        "alt_title"=>"",
        "author_intro"=>"",
        "summary"=>"E組にやってくる2人目の転校生。1人目の律を圧倒的に上回るとされる、その驚くべき暗殺能力とは!? 殺せんせー誕生の謎も徐々に明らかに!!",
        "series"=>array(
          "id"=>"15153",
          "title"=>"暗殺教室"
        ),
        "price"=>"JPY  420"
      ),
      array(
        "rating"=>array(
          "max"=>10,
          "numRaters"=>228,
          "average"=>"9.1",
          "min"=>0
        ),
        "subtitle"=>"",
        "author"=>array(
          "松井優征"
        ),
        "pubdate"=>"2013-7-4",
        "tags"=>array(
          array(
            "count"=>69,
            "name"=>"漫画",
            "title"=>"漫画"
          ),
          array(
            "count"=>44,
            "name"=>"松井優征",
            "title"=>"松井優征"
          ),
          array(
            "count"=>30,
            "name"=>"日本",
            "title"=>"日本"
          ),
          array(
            "count"=>15,
            "name"=>"暗殺教室",
            "title"=>"暗殺教室"
          ),
          array(
            "count"=>15,
            "name"=>"日本漫画",
            "title"=>"日本漫画"
          ),
          array(
            "count"=>12,
            "name"=>"松井优征",
            "title"=>"松井优征"
          ),
          array(
            "count"=>8,
            "name"=>"少年漫画",
            "title"=>"少年漫画"
          ),
          array(
            "count"=>5,
            "name"=>"日漫",
            "title"=>"日漫"
          )
        ),
        "origin_title"=>"",
        "image"=>"https://img3.doubanio.com/view/subject/m/public/s26814304.jpg",
        "binding"=>"コミック",
        "translator"=>array(),
        "catalog"=>"",
        "pages"=>"192",
        "images"=>array(
          "small"=>"https://img3.doubanio.com/view/subject/s/public/s26814304.jpg",
          "large"=>"https://img3.doubanio.com/view/subject/l/public/s26814304.jpg",
          "medium"=>"https://img3.doubanio.com/view/subject/m/public/s26814304.jpg"
        ),
        "alt"=>"https://book.douban.com/subject/24703372/",
        "id"=>"24703372",
        "publisher"=>"集英社",
        "isbn10"=>"4088707699",
        "isbn13"=>"9784088707693",
        "title"=>"暗殺教室 5",
        "url"=>"https://api.douban.com/v2/book/24703372",
        "alt_title"=>"",
        "author_intro"=>"",
        "summary"=>"殺せんせー暗殺を確実なものとするため、防衛省はE組に新しい教師を派遣した。彼は烏間に代わり生徒の訓練担当になるが、常軌を逸した教育方針で!?",
        "series"=>array(
          "id"=>"15153",
          "title"=>"暗殺教室"
        ),
        "price"=>"JPY  420"
      ),
      array(
        "rating"=>array(
          "max"=>10,
          "numRaters"=>156,
          "average"=>"8.8",
          "min"=>0
        ),
        "subtitle"=>"",
        "author"=>array(
          "松井 優征"
        ),
        "pubdate"=>"2013-10-4",
        "tags"=>array(
          array(
            "count"=>47,
            "name"=>"漫画",
            "title"=>"漫画"
          ),
          array(
            "count"=>30,
            "name"=>"松井優征",
            "title"=>"松井優征"
          ),
          array(
            "count"=>21,
            "name"=>"日本",
            "title"=>"日本"
          ),
          array(
            "count"=>13,
            "name"=>"日本漫画",
            "title"=>"日本漫画"
          ),
          array(
            "count"=>9,
            "name"=>"暗殺教室",
            "title"=>"暗殺教室"
          ),
          array(
            "count"=>7,
            "name"=>"松井优征",
            "title"=>"松井优征"
          ),
          array(
            "count"=>4,
            "name"=>"日漫",
            "title"=>"日漫"
          ),
          array(
            "count"=>4,
            "name"=>"少年漫画",
            "title"=>"少年漫画"
          )
        ),
        "origin_title"=>"",
        "image"=>"https://img3.doubanio.com/view/subject/m/public/s27102092.jpg",
        "binding"=>"コミック",
        "translator"=>array(),
        "catalog"=>"",
        "pages"=>"192",
        "images"=>array(
          "small"=>"https://img3.doubanio.com/view/subject/s/public/s27102092.jpg",
          "large"=>"https://img3.doubanio.com/view/subject/l/public/s27102092.jpg",
          "medium"=>"https://img3.doubanio.com/view/subject/m/public/s27102092.jpg"
        ),
        "alt"=>"https://book.douban.com/subject/25737839/",
        "id"=>"25737839",
        "publisher"=>"集英社",
        "isbn10"=>"4088708210",
        "isbn13"=>"9784088708218",
        "title"=>"暗殺教室 6",
        "url"=>"https://api.douban.com/v2/book/25737839",
        "alt_title"=>"",
        "author_intro"=>"",
        "summary"=>"殺せんせー最大の弱点は水!? 水殺の機会を窺うE組の生徒達だが、妨害工作を行う裏切り者が現れる。彼の手引きをしていたのは、あの2人だった──!!",
        "series"=>array(
          "id"=>"15153",
          "title"=>"暗殺教室"
        ),
        "price"=>"JPY 420"
      ),
      array(
        "rating"=>array(
          "max"=>10,
          "numRaters"=>143,
          "average"=>"8.8",
          "min"=>0
        ),
        "subtitle"=>"",
        "author"=>array(
          "松井優征"
        ),
        "pubdate"=>"2013-12-27",
        "tags"=>array(
          array(
            "count"=>39,
            "name"=>"漫画",
            "title"=>"漫画"
          ),
          array(
            "count"=>22,
            "name"=>"松井優征",
            "title"=>"松井優征"
          ),
          array(
            "count"=>18,
            "name"=>"日本",
            "title"=>"日本"
          ),
          array(
            "count"=>12,
            "name"=>"日本漫画",
            "title"=>"日本漫画"
          ),
          array(
            "count"=>10,
            "name"=>"暗殺教室",
            "title"=>"暗殺教室"
          ),
          array(
            "count"=>7,
            "name"=>"松井优征",
            "title"=>"松井优征"
          ),
          array(
            "count"=>6,
            "name"=>"日漫",
            "title"=>"日漫"
          ),
          array(
            "count"=>4,
            "name"=>"少年漫画",
            "title"=>"少年漫画"
          )
        ),
        "origin_title"=>"",
        "image"=>"https://img3.doubanio.com/view/subject/m/public/s27189109.jpg",
        "binding"=>"コミック",
        "translator"=>array(),
        "catalog"=>"",
        "pages"=>"200",
        "images"=>array(
          "small"=>"https://img3.doubanio.com/view/subject/s/public/s27189109.jpg",
          "large"=>"https://img3.doubanio.com/view/subject/l/public/s27189109.jpg",
          "medium"=>"https://img3.doubanio.com/view/subject/m/public/s27189109.jpg"
        ),
        "alt"=>"https://book.douban.com/subject/25757382/",
        "id"=>"25757382",
        "publisher"=>"集英社",
        "isbn10"=>"4088708547",
        "isbn13"=>"9784088708546",
        "title"=>"暗殺教室 7",
        "url"=>"https://api.douban.com/v2/book/25757382",
        "alt_title"=>"",
        "author_intro"=>"",
        "summary"=>"",
        "series"=>array(
          "id"=>"15153",
          "title"=>"暗殺教室"
        ),
        "price"=>"JPY  420"
      ),
      array(
        "rating"=>array(
          "max"=>10,
          "numRaters"=>118,
          "average"=>"8.9",
          "min"=>0
        ),
        "subtitle"=>"",
        "author"=>array(
          "松井 優征"
        ),
        "pubdate"=>"2014-3-4",
        "tags"=>array(
          array(
            "count"=>32,
            "name"=>"漫画",
            "title"=>"漫画"
          ),
          array(
            "count"=>17,
            "name"=>"松井優征",
            "title"=>"松井優征"
          ),
          array(
            "count"=>12,
            "name"=>"日本",
            "title"=>"日本"
          ),
          array(
            "count"=>10,
            "name"=>"暗殺教室",
            "title"=>"暗殺教室"
          ),
          array(
            "count"=>10,
            "name"=>"日本漫画",
            "title"=>"日本漫画"
          ),
          array(
            "count"=>7,
            "name"=>"松井优征",
            "title"=>"松井优征"
          ),
          array(
            "count"=>4,
            "name"=>"日漫",
            "title"=>"日漫"
          ),
          array(
            "count"=>4,
            "name"=>"搞笑",
            "title"=>"搞笑"
          )
        ),
        "origin_title"=>"",
        "image"=>"https://img3.doubanio.com/view/subject/m/public/s27256594.jpg",
        "binding"=>"コミック",
        "translator"=>array(),
        "catalog"=>"",
        "pages"=>"192",
        "images"=>array(
          "small"=>"https://img3.doubanio.com/view/subject/s/public/s27256594.jpg",
          "large"=>"https://img3.doubanio.com/view/subject/l/public/s27256594.jpg",
          "medium"=>"https://img3.doubanio.com/view/subject/m/public/s27256594.jpg"
        ),
        "alt"=>"https://book.douban.com/subject/25828465/",
        "id"=>"25828465",
        "publisher"=>"集英社",
        "isbn10"=>"4088800281",
        "isbn13"=>"9784088800288",
        "title"=>"暗殺教室 8",
        "url"=>"https://api.douban.com/v2/book/25828465",
        "alt_title"=>"",
        "author_intro"=>"",
        "summary"=>"",
        "series"=>array(
          "id"=>"15153",
          "title"=>"暗殺教室"
        ),
        "price"=>"JPY 432"
      ),
      array(
        "rating"=>array(
          "max"=>10,
          "numRaters"=>110,
          "average"=>"8.9",
          "min"=>0
        ),
        "subtitle"=>"",
        "author"=>array(
          "松井 優征"
        ),
        "pubdate"=>"2014-5-2",
        "tags"=>array(
          array(
            "count"=>25,
            "name"=>"漫画",
            "title"=>"漫画"
          ),
          array(
            "count"=>11,
            "name"=>"松井優征",
            "title"=>"松井優征"
          ),
          array(
            "count"=>9,
            "name"=>"日本漫画",
            "title"=>"日本漫画"
          ),
          array(
            "count"=>9,
            "name"=>"日本",
            "title"=>"日本"
          ),
          array(
            "count"=>7,
            "name"=>"暗殺教室",
            "title"=>"暗殺教室"
          ),
          array(
            "count"=>6,
            "name"=>"松井优征",
            "title"=>"松井优征"
          ),
          array(
            "count"=>5,
            "name"=>"日漫",
            "title"=>"日漫"
          ),
          array(
            "count"=>3,
            "name"=>"暗杀教室",
            "title"=>"暗杀教室"
          )
        ),
        "origin_title"=>"",
        "image"=>"https://img3.doubanio.com/view/subject/m/public/s27266902.jpg",
        "binding"=>"コミック",
        "translator"=>array(),
        "catalog"=>"",
        "pages"=>"192",
        "images"=>array(
          "small"=>"https://img3.doubanio.com/view/subject/s/public/s27266902.jpg",
          "large"=>"https://img3.doubanio.com/view/subject/l/public/s27266902.jpg",
          "medium"=>"https://img3.doubanio.com/view/subject/m/public/s27266902.jpg"
        ),
        "alt"=>"https://book.douban.com/subject/25849801/",
        "id"=>"25849801",
        "publisher"=>"集英社",
        "isbn10"=>"4088800591",
        "isbn13"=>"9784088800592",
        "title"=>"暗殺教室 9",
        "url"=>"https://api.douban.com/v2/book/25849801",
        "alt_title"=>"",
        "author_intro"=>"",
        "summary"=>"目の前で治療薬を破壊した鷹岡に激昂する渚。しかし、正面戦闘では暗殺技術は使えず鷹岡に圧倒される。ロヴロ直伝の必殺技で起死回生なるか──!?",
        "series"=>array(
          "id"=>"15153",
          "title"=>"暗殺教室"
        ),
        "price"=>"JPY 432"
      ),
      array(
        "rating"=>array(
          "max"=>10,
          "numRaters"=>100,
          "average"=>"8.9",
          "min"=>0
        ),
        "subtitle"=>"",
        "author"=>array(
          "松井 優征"
        ),
        "pubdate"=>"2014-7-4",
        "tags"=>array(
          array(
            "count"=>24,
            "name"=>"漫画",
            "title"=>"漫画"
          ),
          array(
            "count"=>10,
            "name"=>"松井優征",
            "title"=>"松井優征"
          ),
          array(
            "count"=>9,
            "name"=>"日本漫画",
            "title"=>"日本漫画"
          ),
          array(
            "count"=>7,
            "name"=>"暗殺教室",
            "title"=>"暗殺教室"
          ),
          array(
            "count"=>7,
            "name"=>"日本",
            "title"=>"日本"
          ),
          array(
            "count"=>6,
            "name"=>"松井优征",
            "title"=>"松井优征"
          ),
          array(
            "count"=>5,
            "name"=>"日漫",
            "title"=>"日漫"
          ),
          array(
            "count"=>3,
            "name"=>"暗杀教室",
            "title"=>"暗杀教室"
          )
        ),
        "origin_title"=>"",
        "image"=>"https://img3.doubanio.com/view/subject/m/public/s27313473.jpg",
        "binding"=>"コミック",
        "translator"=>array(),
        "catalog"=>"",
        "pages"=>"192",
        "images"=>array(
          "small"=>"https://img3.doubanio.com/view/subject/s/public/s27313473.jpg",
          "large"=>"https://img3.doubanio.com/view/subject/l/public/s27313473.jpg",
          "medium"=>"https://img3.doubanio.com/view/subject/m/public/s27313473.jpg"
        ),
        "alt"=>"https://book.douban.com/subject/25909102/",
        "id"=>"25909102",
        "publisher"=>"集英社",
        "isbn10"=>"4088801377",
        "isbn13"=>"9784088801377",
        "title"=>"暗殺教室 10",
        "url"=>"https://api.douban.com/v2/book/25909102",
        "alt_title"=>"",
        "author_intro"=>"",
        "summary"=>"殺せんせーに下着ドロ疑惑が!?　殺せんせーは生徒の信頼を取り戻すため、真犯人の捜査に乗り出す。だがこれは、またしても奴等による罠だった――!!",
        "series"=>array(
          "id"=>"15153",
          "title"=>"暗殺教室"
        ),
        "price"=>"JPY 432"
      ),
      array(
        "rating"=>array(
          "max"=>10,
          "numRaters"=>81,
          "average"=>"9.0",
          "min"=>0
        ),
        "subtitle"=>"",
        "author"=>array(
          "松井 優征"
        ),
        "pubdate"=>"2014-10-3",
        "tags"=>array(
          array(
            "count"=>19,
            "name"=>"漫画",
            "title"=>"漫画"
          ),
          array(
            "count"=>9,
            "name"=>"日本漫画",
            "title"=>"日本漫画"
          ),
          array(
            "count"=>7,
            "name"=>"松井優征",
            "title"=>"松井優征"
          ),
          array(
            "count"=>7,
            "name"=>"日本",
            "title"=>"日本"
          ),
          array(
            "count"=>6,
            "name"=>"暗殺教室",
            "title"=>"暗殺教室"
          ),
          array(
            "count"=>4,
            "name"=>"松井优征",
            "title"=>"松井优征"
          ),
          array(
            "count"=>4,
            "name"=>"暗杀教室",
            "title"=>"暗杀教室"
          ),
          array(
            "count"=>4,
            "name"=>"日漫",
            "title"=>"日漫"
          )
        ),
        "origin_title"=>"",
        "image"=>"https://img3.doubanio.com/view/subject/m/public/s27547225.jpg",
        "binding"=>"コミック",
        "translator"=>array(),
        "catalog"=>"",
        "pages"=>"",
        "images"=>array(
          "small"=>"https://img3.doubanio.com/view/subject/s/public/s27547225.jpg",
          "large"=>"https://img3.doubanio.com/view/subject/l/public/s27547225.jpg",
          "medium"=>"https://img3.doubanio.com/view/subject/m/public/s27547225.jpg"
        ),
        "alt"=>"https://book.douban.com/subject/25964090/",
        "id"=>"25964090",
        "publisher"=>"集英社",
        "isbn10"=>"4088801946",
        "isbn13"=>"9784088801940",
        "title"=>"暗殺教室 11",
        "url"=>"https://api.douban.com/v2/book/25964090",
        "alt_title"=>"",
        "author_intro"=>"",
        "summary"=>"暗殺期限まで残り五か月…焦る生徒達は、自らの力を過信し、重大な事件を起こしてしまう。正しい暗殺者であるために、殺せんせーが課した試練とは!?",
        "series"=>array(
          "id"=>"15153",
          "title"=>"暗殺教室"
        ),
        "price"=>"JPY 432"
      ),
      array(
        "rating"=>array(
          "max"=>10,
          "numRaters"=>73,
          "average"=>"9.0",
          "min"=>0
        ),
        "subtitle"=>"",
        "author"=>array(
          "松井優征"
        ),
        "pubdate"=>"2014-12-27",
        "tags"=>array(
          array(
            "count"=>15,
            "name"=>"漫画",
            "title"=>"漫画"
          ),
          array(
            "count"=>8,
            "name"=>"松井優征",
            "title"=>"松井優征"
          ),
          array(
            "count"=>6,
            "name"=>"暗殺教室",
            "title"=>"暗殺教室"
          ),
          array(
            "count"=>6,
            "name"=>"日本漫画",
            "title"=>"日本漫画"
          ),
          array(
            "count"=>5,
            "name"=>"日漫",
            "title"=>"日漫"
          ),
          array(
            "count"=>5,
            "name"=>"日本",
            "title"=>"日本"
          ),
          array(
            "count"=>3,
            "name"=>"松井优征",
            "title"=>"松井优征"
          ),
          array(
            "count"=>3,
            "name"=>"暗杀教室",
            "title"=>"暗杀教室"
          )
        ),
        "origin_title"=>"",
        "image"=>"https://img3.doubanio.com/view/subject/m/public/s27971960.jpg",
        "binding"=>"",
        "translator"=>array(),
        "catalog"=>"",
        "pages"=>"192",
        "images"=>array(
          "small"=>"https://img3.doubanio.com/view/subject/s/public/s27971960.jpg",
          "large"=>"https://img3.doubanio.com/view/subject/l/public/s27971960.jpg",
          "medium"=>"https://img3.doubanio.com/view/subject/m/public/s27971960.jpg"
        ),
        "alt"=>"https://book.douban.com/subject/26261268/",
        "id"=>"26261268",
        "publisher"=>"集英社",
        "isbn10"=>"4088802233",
        "isbn13"=>"9784088802237",
        "title"=>"暗殺教室 12",
        "url"=>"https://api.douban.com/v2/book/26261268",
        "alt_title"=>"",
        "author_intro"=>"",
        "summary"=>"E組生徒に支給された新しい体育着は、世界最高の性能を誇る代物だった。暗殺の幅が大きく広がった生徒達に忍び寄る黒い影が…。殺し屋“死神\"襲来!!",
        "series"=>array(
          "id"=>"15153",
          "title"=>"暗殺教室"
        ),
        "price"=>"JPY 432"
      ),
      array(
        "rating"=>array(
          "max"=>10,
          "numRaters"=>64,
          "average"=>"8.8",
          "min"=>0
        ),
        "subtitle"=>"",
        "author"=>array(
          "松井 優征"
        ),
        "pubdate"=>"2015-3-4",
        "tags"=>array(
          array(
            "count"=>16,
            "name"=>"漫画",
            "title"=>"漫画"
          ),
          array(
            "count"=>6,
            "name"=>"暗殺教室",
            "title"=>"暗殺教室"
          ),
          array(
            "count"=>6,
            "name"=>"日本",
            "title"=>"日本"
          ),
          array(
            "count"=>5,
            "name"=>"松井优征",
            "title"=>"松井优征"
          ),
          array(
            "count"=>4,
            "name"=>"日本漫画",
            "title"=>"日本漫画"
          ),
          array(
            "count"=>3,
            "name"=>"松井優征",
            "title"=>"松井優征"
          ),
          array(
            "count"=>3,
            "name"=>"日漫",
            "title"=>"日漫"
          ),
          array(
            "count"=>2,
            "name"=>"暗杀教室",
            "title"=>"暗杀教室"
          )
        ),
        "origin_title"=>"",
        "image"=>"https://img3.doubanio.com/view/subject/m/public/s28015636.jpg",
        "binding"=>"コミック",
        "translator"=>array(),
        "catalog"=>"",
        "pages"=>"",
        "images"=>array(
          "small"=>"https://img3.doubanio.com/view/subject/s/public/s28015636.jpg",
          "large"=>"https://img3.doubanio.com/view/subject/l/public/s28015636.jpg",
          "medium"=>"https://img3.doubanio.com/view/subject/m/public/s28015636.jpg"
        ),
        "alt"=>"https://book.douban.com/subject/26308640/",
        "id"=>"26308640",
        "publisher"=>"集英社",
        "isbn10"=>"4088803175",
        "isbn13"=>"9784088803173",
        "title"=>"暗殺教室 13",
        "url"=>"https://api.douban.com/v2/book/26308640",
        "alt_title"=>"",
        "author_intro"=>"",
        "summary"=>"殺せんせー暗殺に成功したその先は? 進路相談を行う事になったE組だが、渚は自分の才能の事で迷っていた。そして帰宅した渚を待っていたのは…!?",
        "series"=>array(
          "id"=>"15153",
          "title"=>"暗殺教室"
        ),
        "price"=>"JPY 432"
      ),
      array(
        "rating"=>array(
          "max"=>10,
          "numRaters"=>60,
          "average"=>"9.0",
          "min"=>0
        ),
        "subtitle"=>"",
        "author"=>array(
          "松井　優征"
        ),
        "pubdate"=>"2015-5-1",
        "tags"=>array(
          array(
            "count"=>15,
            "name"=>"漫画",
            "title"=>"漫画"
          ),
          array(
            "count"=>6,
            "name"=>"松井優征",
            "title"=>"松井優征"
          ),
          array(
            "count"=>6,
            "name"=>"暗殺教室",
            "title"=>"暗殺教室"
          ),
          array(
            "count"=>6,
            "name"=>"日本",
            "title"=>"日本"
          ),
          array(
            "count"=>4,
            "name"=>"日漫",
            "title"=>"日漫"
          ),
          array(
            "count"=>4,
            "name"=>"日本漫画",
            "title"=>"日本漫画"
          ),
          array(
            "count"=>3,
            "name"=>"松井优征",
            "title"=>"松井优征"
          ),
          array(
            "count"=>3,
            "name"=>"暗杀教室",
            "title"=>"暗杀教室"
          )
        ),
        "origin_title"=>"",
        "image"=>"https://img3.doubanio.com/view/subject/m/public/s28061606.jpg",
        "binding"=>"コミック",
        "translator"=>array(),
        "catalog"=>"",
        "pages"=>"192",
        "images"=>array(
          "small"=>"https://img3.doubanio.com/view/subject/s/public/s28061606.jpg",
          "large"=>"https://img3.doubanio.com/view/subject/l/public/s28061606.jpg",
          "medium"=>"https://img3.doubanio.com/view/subject/m/public/s28061606.jpg"
        ),
        "alt"=>"https://book.douban.com/subject/26345850/",
        "id"=>"26345850",
        "publisher"=>"集英社",
        "isbn10"=>"408880354X",
        "isbn13"=>"9784088803548",
        "title"=>"暗殺教室  14",
        "url"=>"https://api.douban.com/v2/book/26345850",
        "alt_title"=>"",
        "author_intro"=>"",
        "summary"=>"期末テストに向けて、浅野理事長がA組の担任に! E組への憎悪を煽る異様な授業風景を見て、息子・学秀はE組にある依頼を持ちこむ。その狙いは…!?",
        "series"=>array(
          "id"=>"15153",
          "title"=>"暗殺教室"
        ),
        "price"=>"JPY 432"
      ),
      array(
        "rating"=>array(
          "max"=>10,
          "numRaters"=>56,
          "average"=>"8.8",
          "min"=>0
        ),
        "subtitle"=>"",
        "author"=>array(
          "松井　優征"
        ),
        "pubdate"=>"2015-7-3",
        "tags"=>array(
          array(
            "count"=>13,
            "name"=>"漫画",
            "title"=>"漫画"
          ),
          array(
            "count"=>5,
            "name"=>"暗殺教室",
            "title"=>"暗殺教室"
          ),
          array(
            "count"=>5,
            "name"=>"日本",
            "title"=>"日本"
          ),
          array(
            "count"=>4,
            "name"=>"日漫",
            "title"=>"日漫"
          ),
          array(
            "count"=>4,
            "name"=>"日本漫画",
            "title"=>"日本漫画"
          ),
          array(
            "count"=>3,
            "name"=>"松井优征",
            "title"=>"松井优征"
          ),
          array(
            "count"=>3,
            "name"=>"暗杀教室",
            "title"=>"暗杀教室"
          ),
          array(
            "count"=>2,
            "name"=>"松井優征",
            "title"=>"松井優征"
          )
        ),
        "origin_title"=>"",
        "image"=>"https://img3.doubanio.com/view/subject/m/public/s28122778.jpg",
        "binding"=>"",
        "translator"=>array(),
        "catalog"=>"",
        "pages"=>"",
        "images"=>array(
          "small"=>"https://img3.doubanio.com/view/subject/s/public/s28122778.jpg",
          "large"=>"https://img3.doubanio.com/view/subject/l/public/s28122778.jpg",
          "medium"=>"https://img3.doubanio.com/view/subject/m/public/s28122778.jpg"
        ),
        "alt"=>"https://book.douban.com/subject/26394448/",
        "id"=>"26394448",
        "publisher"=>"集英社",
        "isbn10"=>"4088804252",
        "isbn13"=>"9784088804255",
        "title"=>"暗殺教室 15",
        "url"=>"https://api.douban.com/v2/book/26394448",
        "alt_title"=>"",
        "author_intro"=>"",
        "summary"=>"",
        "series"=>array(
          "id"=>"15153",
          "title"=>"暗殺教室"
        ),
        "price"=>"JPY 432"
      ),
      array(
        "rating"=>array(
          "max"=>10,
          "numRaters"=>43,
          "average"=>"9.0",
          "min"=>0
        ),
        "subtitle"=>"",
        "author"=>array(
          "松井 優征"
        ),
        "pubdate"=>"2015-10-3",
        "tags"=>array(
          array(
            "count"=>10,
            "name"=>"漫画",
            "title"=>"漫画"
          ),
          array(
            "count"=>5,
            "name"=>"暗殺教室",
            "title"=>"暗殺教室"
          ),
          array(
            "count"=>4,
            "name"=>"暗杀教室",
            "title"=>"暗杀教室"
          ),
          array(
            "count"=>3,
            "name"=>"日本漫画",
            "title"=>"日本漫画"
          ),
          array(
            "count"=>2,
            "name"=>"松井優征",
            "title"=>"松井優征"
          ),
          array(
            "count"=>2,
            "name"=>"松井优征",
            "title"=>"松井优征"
          ),
          array(
            "count"=>2,
            "name"=>"日漫",
            "title"=>"日漫"
          ),
          array(
            "count"=>2,
            "name"=>"日本",
            "title"=>"日本"
          )
        ),
        "origin_title"=>"",
        "image"=>"https://img3.doubanio.com/view/subject/m/public/s28307734.jpg",
        "binding"=>"コミック",
        "translator"=>array(),
        "catalog"=>"",
        "pages"=>"192",
        "images"=>array(
          "small"=>"https://img3.doubanio.com/view/subject/s/public/s28307734.jpg",
          "large"=>"https://img3.doubanio.com/view/subject/l/public/s28307734.jpg",
          "medium"=>"https://img3.doubanio.com/view/subject/m/public/s28307734.jpg"
        ),
        "alt"=>"https://book.douban.com/subject/26594434/",
        "id"=>"26594434",
        "publisher"=>"集英社",
        "isbn10"=>"4088804856",
        "isbn13"=>"9784088804859",
        "title"=>"暗殺教室 16",
        "url"=>"https://api.douban.com/v2/book/26594434",
        "alt_title"=>"",
        "author_intro"=>"",
        "summary"=>"",
        "series"=>array(
          "id"=>"15153",
          "title"=>"暗殺教室"
        ),
        "price"=>"JPY 432"
      ),
      array(
        "rating"=>array(
          "max"=>10,
          "numRaters"=>39,
          "average"=>"8.8",
          "min"=>0
        ),
        "subtitle"=>"",
        "author"=>array(
          "松井 優征"
        ),
        "pubdate"=>"2015-12-28",
        "tags"=>array(
          array(
            "count"=>8,
            "name"=>"漫画",
            "title"=>"漫画"
          ),
          array(
            "count"=>6,
            "name"=>"暗殺教室",
            "title"=>"暗殺教室"
          ),
          array(
            "count"=>4,
            "name"=>"松井优征",
            "title"=>"松井优征"
          ),
          array(
            "count"=>4,
            "name"=>"暗杀教室",
            "title"=>"暗杀教室"
          ),
          array(
            "count"=>4,
            "name"=>"日本漫画",
            "title"=>"日本漫画"
          ),
          array(
            "count"=>3,
            "name"=>"日漫",
            "title"=>"日漫"
          ),
          array(
            "count"=>2,
            "name"=>"松井優征",
            "title"=>"松井優征"
          ),
          array(
            "count"=>2,
            "name"=>"日本",
            "title"=>"日本"
          )
        ),
        "origin_title"=>"",
        "image"=>"https://img3.doubanio.com/view/subject/m/public/s28371133.jpg",
        "binding"=>"コミック",
        "translator"=>array(),
        "catalog"=>"",
        "pages"=>"200",
        "images"=>array(
          "small"=>"https://img3.doubanio.com/view/subject/s/public/s28371133.jpg",
          "large"=>"https://img3.doubanio.com/view/subject/l/public/s28371133.jpg",
          "medium"=>"https://img3.doubanio.com/view/subject/m/public/s28371133.jpg"
        ),
        "alt"=>"https://book.douban.com/subject/26647300/",
        "id"=>"26647300",
        "publisher"=>"集英社",
        "isbn10"=>"408880581X",
        "isbn13"=>"9784088805818",
        "title"=>"暗殺教室 17",
        "url"=>"https://api.douban.com/v2/book/26647300",
        "alt_title"=>"",
        "author_intro"=>"",
        "summary"=>"",
        "series"=>array(
          "id"=>"15153",
          "title"=>"暗殺教室"
        ),
        "price"=>"JPY 432"
      ),
      array(
        "rating"=>array(
          "max"=>10,
          "numRaters"=>41,
          "average"=>"8.9",
          "min"=>0
        ),
        "subtitle"=>"",
        "author"=>array(
          "松井　優征"
        ),
        "pubdate"=>"2016-3-4",
        "tags"=>array(
          array(
            "count"=>8,
            "name"=>"漫画",
            "title"=>"漫画"
          ),
          array(
            "count"=>5,
            "name"=>"暗殺教室",
            "title"=>"暗殺教室"
          ),
          array(
            "count"=>4,
            "name"=>"松井优征",
            "title"=>"松井优征"
          ),
          array(
            "count"=>4,
            "name"=>"暗杀教室",
            "title"=>"暗杀教室"
          ),
          array(
            "count"=>3,
            "name"=>"日本",
            "title"=>"日本"
          ),
          array(
            "count"=>2,
            "name"=>"松井優征",
            "title"=>"松井優征"
          ),
          array(
            "count"=>2,
            "name"=>"日漫",
            "title"=>"日漫"
          ),
          array(
            "count"=>2,
            "name"=>"日本漫画",
            "title"=>"日本漫画"
          )
        ),
        "origin_title"=>"",
        "image"=>"https://img3.doubanio.com/view/subject/m/public/s28487551.jpg",
        "binding"=>"コミック",
        "translator"=>array(),
        "catalog"=>"",
        "pages"=>"192",
        "images"=>array(
          "small"=>"https://img3.doubanio.com/view/subject/s/public/s28487551.jpg",
          "large"=>"https://img3.doubanio.com/view/subject/l/public/s28487551.jpg",
          "medium"=>"https://img3.doubanio.com/view/subject/m/public/s28487551.jpg"
        ),
        "alt"=>"https://book.douban.com/subject/26712660/",
        "id"=>"26712660",
        "publisher"=>"集英社",
        "isbn10"=>"4088806271",
        "isbn13"=>"9784088806273",
        "title"=>"暗殺教室  18",
        "url"=>"https://api.douban.com/v2/book/26712660",
        "alt_title"=>"",
        "author_intro"=>"",
        "summary"=>"",
        "series"=>array(
          "id"=>"15153",
          "title"=>"暗殺教室"
        ),
        "price"=>"JPY 432"
      ),
      array(
        "rating"=>array(
          "max"=>10,
          "numRaters"=>37,
          "average"=>"9.5",
          "min"=>0
        ),
        "subtitle"=>"",
        "author"=>array(
          "松井優征"
        ),
        "pubdate"=>"2016-4-4",
        "tags"=>array(
          array(
            "count"=>8,
            "name"=>"漫画",
            "title"=>"漫画"
          ),
          array(
            "count"=>5,
            "name"=>"暗殺教室",
            "title"=>"暗殺教室"
          ),
          array(
            "count"=>3,
            "name"=>"日漫",
            "title"=>"日漫"
          ),
          array(
            "count"=>3,
            "name"=>"日本漫画",
            "title"=>"日本漫画"
          ),
          array(
            "count"=>2,
            "name"=>"松井優征",
            "title"=>"松井優征"
          ),
          array(
            "count"=>2,
            "name"=>"松井优征",
            "title"=>"松井优征"
          ),
          array(
            "count"=>2,
            "name"=>"暗杀教室",
            "title"=>"暗杀教室"
          ),
          array(
            "count"=>2,
            "name"=>"Manga",
            "title"=>"Manga"
          )
        ),
        "origin_title"=>"",
        "image"=>"https://img3.doubanio.com/view/subject/m/public/s28586026.jpg",
        "binding"=>"コミック",
        "translator"=>array(),
        "catalog"=>"",
        "pages"=>"192",
        "images"=>array(
          "small"=>"https://img3.doubanio.com/view/subject/s/public/s28586026.jpg",
          "large"=>"https://img3.doubanio.com/view/subject/l/public/s28586026.jpg",
          "medium"=>"https://img3.doubanio.com/view/subject/m/public/s28586026.jpg"
        ),
        "alt"=>"https://book.douban.com/subject/26742619/",
        "id"=>"26742619",
        "publisher"=>"集英社",
        "isbn10"=>"4088806514",
        "isbn13"=>"9784088806518",
        "title"=>"暗殺教室 19",
        "url"=>"https://api.douban.com/v2/book/26742619",
        "alt_title"=>"",
        "author_intro"=>"",
        "summary"=>"",
        "series"=>array(
          "id"=>"15153",
          "title"=>"暗殺教室"
        ),
        "price"=>"JPY 400"
      ),
      array(
        "rating"=>array(
          "max"=>10,
          "numRaters"=>40,
          "average"=>"9.6",
          "min"=>0
        ),
        "subtitle"=>"",
        "author"=>array(
          "松井優征"
        ),
        "pubdate"=>"2016-6-3",
        "tags"=>array(
          array(
            "count"=>7,
            "name"=>"漫画",
            "title"=>"漫画"
          ),
          array(
            "count"=>5,
            "name"=>"暗殺教室",
            "title"=>"暗殺教室"
          ),
          array(
            "count"=>4,
            "name"=>"暗杀教室",
            "title"=>"暗杀教室"
          ),
          array(
            "count"=>3,
            "name"=>"松井优征",
            "title"=>"松井优征"
          ),
          array(
            "count"=>3,
            "name"=>"日漫",
            "title"=>"日漫"
          ),
          array(
            "count"=>2,
            "name"=>"电子版",
            "title"=>"电子版"
          ),
          array(
            "count"=>2,
            "name"=>"日本",
            "title"=>"日本"
          ),
          array(
            "count"=>2,
            "name"=>"Manga",
            "title"=>"Manga"
          )
        ),
        "origin_title"=>"",
        "image"=>"https://img3.doubanio.com/view/subject/m/public/s28881049.jpg",
        "binding"=>"",
        "translator"=>array(),
        "catalog"=>"",
        "pages"=>"184",
        "images"=>array(
          "small"=>"https://img3.doubanio.com/view/subject/s/public/s28881049.jpg",
          "large"=>"https://img3.doubanio.com/view/subject/l/public/s28881049.jpg",
          "medium"=>"https://img3.doubanio.com/view/subject/m/public/s28881049.jpg"
        ),
        "alt"=>"https://book.douban.com/subject/26833087/",
        "id"=>"26833087",
        "publisher"=>"集英社",
        "isbn10"=>"4088806867",
        "isbn13"=>"9784088806860",
        "title"=>"暗殺教室 20",
        "url"=>"https://api.douban.com/v2/book/26833087",
        "alt_title"=>"",
        "author_intro"=>"",
        "summary"=>"殺せんせーと感動の再会を果たした生徒達。しかし激しい憎悪から生まれた2人の怪物が迫り来る。最後の闘いの行方は!? そして生徒達は──",
        "series"=>array(
          "id"=>"15153",
          "title"=>"暗殺教室"
        ),
        "price"=>"JPY 400"
      )
    )
      );
      return $books;
}